INSERT INTO brands (name)
VALUES  ('Праймбиф'),
        ('Мираторг'),
        ('Азбука Вкуса'),
        ('Пава-Пава'),
        ('Петелинка'),
        ('Margot Fromages'),
        ('President'),
        ('Hacker-Pschorr'),
        ('Spaten'),
        ('Pilsner Urquell'),
        ('Krusovice'),
        ('Bernard'),
        ('Corona'),
        ('Юкра'),
        ('СИК'),
        ('Agama'),
        ('Бухта Изобилия'),
        ('Borealis'),
        ('Чистая Линия');